Fix entry table view more style bug (#94)
jrdegreeff/health-portrait pull request #100
Opened 2022-12-12 02:39 UTC by wli-linda

2022-12-12 21:35 UTC, jrdegreeff requested changes

2022-12-12 21:35 UTC, jrdegreeff commented on client/components/common/BaseForm.vue
> +        <option
This feels very hacky to me and not generic. what is the intended result?

2022-12-12 21:35 UTC, jrdegreeff commented on client/components/common/BaseForm.vue
> +        !f.optional && this.$helpers.validators.nonEmpty,
I'd rather not add this since we already added in all the other specific places

2022-12-12 21:35 UTC, jrdegreeff commented on client/components/common/BaseForm.vue
> +    },
as above, I don't think this should be here.

2022-12-12 21:49 UTC, wli-linda commented on client/components/common/BaseForm.vue
> +        !f.optional && this.$helpers.validators.nonEmpty,
would it be better to just have it here and remove from specific places? I can't think of a good reason for why required fields could be empty / why optional fields need to be nonEmpty

2022-12-12 22:22 UTC, jrdegreeff submitted a review, later dismissed

2022-12-12 22:30 UTC, jrdegreeff commented on client/components/common/BaseForm.vue
> +        !f.optional && this.$helpers.validators.nonEmpty,
that would be reasonable as well. I'm going offline now, but feel free to do it that way across the board if you prefer.  My only objection is to the duplication.

2022-12-13 04:36 UTC, jrdegreeff approved these changes
looks good. I like the simple workaround for #96.

2022-12-13 04:46 UTC, merged